package calibre;

import Calibre.connection.config;
import calibre.data.OtherFeaturesDataHandler;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Curtin ID : 20205021
 *
 * @author : Tavish Dilmin Perera Dawatage
 * @version : 3.0
 */
public class User extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    //Singleton object
    OtherFeaturesDataHandler dataHandler;

    String username;
    String currentPassword;

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        this.icon2.setVisible(false);
        this.icon4.setVisible(false);

        User.this.setResizable(false);

        conn = config.connectDB();

        //Initialize Singleton object
        dataHandler = OtherFeaturesDataHandler.getDataHandlerInstance();

        //Get username from the Singleton object
        username = dataHandler.getUsername();

        //Get password from the Singleton object
        currentPassword = dataHandler.getPassword();

        //Get Data from the database
        User.this.fetchDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        labelNameUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profileUsername = new javax.swing.JTextField();
        profileEmail = new javax.swing.JTextField();
        profilePassword = new javax.swing.JPasswordField();
        profileCPassword = new javax.swing.JPasswordField();
        browseButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        profileImg = new javax.swing.JLabel();
        profileId = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Details");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/calibre/images/CalibreLogo.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/hidden.png"))); // NOI18N
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon4MousePressed(evt);
            }
        });
        getContentPane().add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 30, 30));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/hidden.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 30, 50));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/visible.png"))); // NOI18N
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon3MousePressed(evt);
            }
        });
        getContentPane().add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 30, 30));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/visible.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 30, 50));

        labelNameUser.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelNameUser.setText("User Details");
        getContentPane().add(labelNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("E - mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        profileUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        profileUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(profileUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 320, 30));

        profileEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(profileEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, 30));

        profilePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(profilePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 320, 30));

        profileCPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(profileCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 320, 30));

        browseButton.setBackground(new java.awt.Color(0, 255, 255));
        browseButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        browseButton.setText("Browse");
        browseButton.setToolTipText("Click to Browse");
        browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseButtonMouseClicked(evt);
            }
        });
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(browseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 90, 30));

        deleteButton.setBackground(new java.awt.Color(0, 255, 255));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.setToolTipText("Click to Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 140, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        profileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibre/images/user.png"))); // NOI18N
        getContentPane().add(profileImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        profileId.setEditable(false);
        getContentPane().add(profileId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 320, 30));

        updateButton.setBackground(new java.awt.Color(0, 255, 255));
        updateButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.setToolTipText("Click to Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 140, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/bgImg.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileUsernameActionPerformed

    }//GEN-LAST:event_profileUsernameActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked

        String passwordConfirm = JOptionPane.showInputDialog("Please Enter you password");
        if (passwordConfirm.equals(profilePassword.getText())) {
            deleteFunction();
            JOptionPane.showConfirmDialog(null, "Profile Deleted", "Alert", JOptionPane.CLOSED_OPTION);
            new LoginToContinue().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void browseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMouseClicked

    }//GEN-LAST:event_browseButtonMouseClicked

    //Password hidden icons
    //Obtaiined from Youtube, https://youtu.be/yFljqVmDgh0
    //(accessed 1 May 2020)
    private void icon4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MousePressed
        icon3.setVisible(true);
        icon4.setVisible(false);
        profileCPassword.setEchoChar('*');
    }//GEN-LAST:event_icon4MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        icon1.setVisible(true);
        icon2.setVisible(false);
        profilePassword.setEchoChar('*');
    }//GEN-LAST:event_icon2MousePressed

    private void icon3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MousePressed
        String passwordConfirm = JOptionPane.showInputDialog("Please Enter you password");
        if (passwordConfirm.equals(currentPassword)) {
            icon4.setVisible(true);
            icon3.setVisible(false);
            profileCPassword.setEchoChar((char) 0);
        } else {
            JOptionPane.showMessageDialog(null, "Password Incorrect", "Alert", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_icon3MousePressed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        String passwordConfirm = JOptionPane.showInputDialog("Please Enter you password");
        if (passwordConfirm.equals(currentPassword)) {
            icon2.setVisible(true);
            icon1.setVisible(false);
            profilePassword.setEchoChar((char) 0);
        } else {
            JOptionPane.showMessageDialog(null, "Password Incorrect", "Alert", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_icon1MousePressed

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked

        if (profileUsername.getText().trim().length() == 0 || profilePassword.getText().trim().length() == 0
                || profileEmail.getText().trim().length() == 0 || profileCPassword.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "All fields are required", "Alert", JOptionPane.CLOSED_OPTION);
        } else {
            int updateResponse = JOptionPane.showConfirmDialog(null, "Do you want to update details", "Alert", JOptionPane.YES_NO_OPTION);
            if (updateResponse == JOptionPane.YES_OPTION) {
                String passwordConfirm = JOptionPane.showInputDialog("Please Enter Current Password ");
                if (passwordConfirm.equals(currentPassword)) {
                    validation();
                } else {
                    JOptionPane.showMessageDialog(null, "Password Incorrect", "Alert", JOptionPane.CLOSED_OPTION);
                }

            } else {
                fetchDetails();
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // Obtaiined from Youtube, https://youtu.be/nVWXJ3qqi0o
        //(accessed 10 May 2020)
        final JFileChooser picChooser = new JFileChooser();

        FileNameExtensionFilter image = new FileNameExtensionFilter("JPEG", "PNG");
        picChooser.setFileFilter(image);

        int option = picChooser.showOpenDialog(picChooser);
        String filename = null;

        if (option == JFileChooser.APPROVE_OPTION) {
            filename = picChooser.getSelectedFile().getAbsolutePath();
            Path path = Paths.get(filename);
            browseButton.setText(path.getFileName().toString());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    //viewDetailsFunction & fetchDetails 
    //Obtaiined from Youtube, https://youtu.be/gdKTxaHBOdA
    //(accessed 14 April 2020)
    public class viewDetailsFunction {

        ResultSet rs = null;

        public ResultSet find(String s) {

            try {

                String view = "SELECT * FROM users WHERE user_Name = ? ";

                pst = conn.prepareStatement(view);

                pst.setString(1, s);

                rs = pst.executeQuery();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            return rs;
        }
    }

    public void fetchDetails() {

        viewDetailsFunction function = new viewDetailsFunction();

        ResultSet rs = null;

        rs = function.find(username);

        try {

            if (rs.next()) {

                profileId.setText(rs.getString("user_Id"));
                profileUsername.setText(rs.getString("user_Name"));
                profileEmail.setText(rs.getString("user_Email"));
                profilePassword.setText(rs.getString("user_password"));
                profileCPassword.setText(rs.getString("user_password"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    //Obtaiined from Youtube, https://youtu.be/ccQDinbe9uk
    //(accessed 14 April 2020)
    public void deleteFunction() {

        try {

            String delete = "DELETE FROM users WHERE user_id = ? ";

            pst = conn.prepareStatement(delete);

            pst.setString(1, profileId.getText());

            pst.execute();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    //Obtaiined from Youtube,  https://youtu.be/qiZrtMfs7tw
    //(accessed 14 April 2020)
    public void updateFunction() {

        try {

            String value1 = profileId.getText();
            String value2 = profileUsername.getText();
            String value3 = profileEmail.getText();
            String value4 = profilePassword.getText();

            String update = "UPDATE users SET user_Name='" + value2 + "',user_Email='" + value3 + "',user_Password='" + value4 + "' WHERE user_Id='" + value1 + "' ";

            pst = conn.prepareStatement(update);

            pst.execute();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //Password Patterns
    // Obtaiined from Java Code Geeks, https://examples.javacodegeeks.com/core-java/util/regex/matcher/validate-password-with-java-regular-expression-example/
    //(accessed 20 April 2020)
    
    //Email Patterns
    // Obtaiined from tutorialspoint, https://www.tutorialspoint.com/validate-email-address-in-java
    //(accessed 20 April 2020)
    public void validation() {

        if (profileUsername.getText().trim().length() == 0 || profilePassword.getText().trim().length() == 0
                || profileEmail.getText().trim().length() == 0 || profileCPassword.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", profileEmail.getText()))) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("((?=.*[a-z])(?=.*\\d)(?=.*[A-Z])(?=.*[@#$%!]).{8,40})", profilePassword.getText()))) {
            JOptionPane.showMessageDialog(null, "The password must be 8 to 40 "
                    + "long and should contain a Capital letter, Simple letter, Number and Special Character", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (profilePassword.getText().equals(profileCPassword.getText())) {
                updateFunction();
                JOptionPane.showConfirmDialog(null, "Details Updated", "Alert", JOptionPane.CLOSED_OPTION);
                new LoginToContinue().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Passwords Dosn't match", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelNameUser;
    public static javax.swing.JPasswordField profileCPassword;
    private javax.swing.JTextField profileEmail;
    public static javax.swing.JTextField profileId;
    private javax.swing.JLabel profileImg;
    public static javax.swing.JPasswordField profilePassword;
    public static javax.swing.JTextField profileUsername;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
