package calibre;

import calibre.data.OtherFeaturesDataHandler;
import com.formdev.flatlaf.IntelliJTheme;
import javax.swing.JOptionPane;

/**
 * Curtin ID : 20205021 *
 * @author : Tavish Dilmin Perera Dawatage
 * @version : 3.0
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    OtherFeaturesDataHandler dataHandler;

    public Welcome() {
        initComponents();

        dataHandler = OtherFeaturesDataHandler.getDataHandlerInstance();

        //Set the default/saved theme
        IntelliJTheme.install(Home.class.getResourceAsStream("/calibre/themes/Cyan.theme.json"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/calibre/images/CalibreLogo.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/loader.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calibre/images/Welcome Page.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Obtaiined from youtube, https://youtu.be/Np2zG0DgyUM
        //(accessed 10 April 2020)
        Welcome welcome = new Welcome();
        welcome.setVisible(true);
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(5);
                if (i == 100) {
                    LoginToContinue loginToContinue = new LoginToContinue();
                    welcome.setVisible(false);
                    loginToContinue.setVisible(true);
                }
            }
        } catch (InterruptedException e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
